apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: env-printer-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: env-printer
    http:
      paths:
      - path: /
        backend:
          serviceName: env-printer-app
          servicePort: 8080
