apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - image: twyla.io/simple-python-app:v0.0.1
          imagePullPolicy: IfNotPresent
          name: simple-python-app
