apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-python-app
  namespace: twyla
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - image: twyla.io/simple-python-app:0.0.1
        imagePullPolicy: Never
        name: ??
